environment:
  matrix:
    - REL_DBG: Release
    - REL_DBG: Debug

install:
  #
  # Set compiler environment for MSVC first.
  #
  - cmd: call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
    - cmd: appveyor-script.bat build

test_script:
    - cmd: appveyor-script.bat test

