environment:
  global:
    CPU: x86
  matrix:
    - REL_DBG: Release
    - REL_DBG: Debug

install:
  #
  # Set compiler environment for MSVC first.
  # And start the CoreTemp program.
  #
  - cmd: call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: start Ci\CoreTemp.exe

build_script:
    - cmd: appveyor-script.bat build

test_script:
    - cmd: appveyor-script.bat test

