name: gcc/MinGW CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        BUILD_PLATFORM:  [ x86, x64 ]

    steps:
    - uses: actions/checkout@v2
    - name: GNU-make
      run: make -f Makefile.MinGW FORTIFY_SOURCE=0 CPU=${{matrix.BUILD_PLATFORM}} -C ./src
